version: "3.9"

services:
  backend:
    build: ./app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DATA_DIR=/data
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
  frontend:
    build: ./web
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
